#!/usr/bin/env node
// natlang compiler — reads natural language, emits target code
// The compiler is an LLM. The source is English. The output is code.
//
// Usage:
//   natlang compile hello.nl                    # compile to default target (js)
//   natlang compile hello.nl --target py        # compile to Python
//   natlang compile hello.nl --target rust      # compile to Rust
//   natlang compile hello.nl --target html      # compile to HTML/CSS/JS
//   natlang compile hello.nl --run               # compile and execute
//   natlang run hello.nl                         # shorthand for --run
//
// The .nl file is plain natural language. The compiler reads it and emits code.

import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { resolve, dirname, join, basename, extname } from "path";
import { execSync, spawnSync } from "child_process";

const S = {
  reset: "\x1b[0m", bold: "\x1b[1m", dim: "\x1b[2m",
  green: "\x1b[32m", yellow: "\x1b[33m", cyan: "\x1b[36m", red: "\x1b[31m",
};

// ─────────────────────────────────────────────────────────────────────
// TARGET TEMPLATES — how natlang describes programs for each target
// ─────────────────────────────────────────────────────────────────────

const TARGETS = {
  js: {
    name: "JavaScript (Node.js)",
    extension: ".js",
    preamble: `// Generated by natlang — natural language compiler
// Source: {SOURCE}
// Target: JavaScript (Node.js)
// Compiled: {TIMESTAMP}
// Confidence: {CONFIDENCE}

`,
    runner: "node",
  },
  py: {
    name: "Python",
    extension: ".py",
    preamble: `# Generated by natlang — natural language compiler
# Source: {SOURCE}
# Target: Python
# Compiled: {TIMESTAMP}
# Confidence: {CONFIDENCE}

`,
    runner: "python3",
  },
  rust: {
    name: "Rust",
    extension: ".rs",
    preamble: `// Generated by natlang — natural language compiler
// Source: {SOURCE}
// Target: Rust
// Compiled: {TIMESTAMP}
// Confidence: {CONFIDENCE}

`,
    runner: "rustc",
  },
  html: {
    name: "HTML/CSS/JS",
    extension: ".html",
    preamble: `<!-- Generated by natlang — natural language compiler -->
<!-- Source: {SOURCE} -->
<!-- Target: HTML/CSS/JS -->
<!-- Compiled: {TIMESTAMP} -->
<!-- Confidence: {CONFIDENCE} -->

`,
    runner: null, // HTML is not "run" — it's opened
  },
};

// ─────────────────────────────────────────────────────────────────────
// THE COMPILER — reads natural language, asks an LLM, emits code
// ─────────────────────────────────────────────────────────────────────

async function compile(source, target, sourcePath) {
  const targetInfo = TARGETS[target] || TARGETS.js;

  // The compilation prompt — this is where natlang lives or dies.
  // The prompt must be precise enough to produce deterministic output,
  // but soft enough to read real natural language.
  const prompt = `You are the natlang compiler. You read natural language source code and emit ${targetInfo.name}.

RULES:
1. Read the source as a program specification. Every sentence is an instruction.
2. Emit ONLY executable ${targetInfo.name} code. No markdown fences, no explanation.
3. If the source says "create a web server," emit a working web server.
4. If the source says "when someone visits /hello," emit a route handler.
5. If the source says "respond with X," emit the response code.
6. Use the standard library. No external dependencies unless the source names them.
7. The code must run as-is. No placeholders, no TODOs, no "implement this."
8. If the source is ambiguous, make the simplest interpretation and add a comment: // natlang: assumed X (could also mean Y).
9. State your confidence as a comment at the top: // Confidence: high|medium|low
10. The artifact tells the truth about its own state (Clear Standard #1).

SOURCE:
${source}

Emit ${targetInfo.name} code now:`;

  // Call the LLM via the hermes CLI (or any OpenAI-compatible endpoint)
  // For now, we use the hermes chat command for compilation
  const escapedSource = source.replace(/'/g, "'\\''");

  try {
    const result = spawnSync("hermes", [
      "chat", "-q",
      "--model", "glm-5.2:cloud",
      "-t", "terminal",
      "--yolo",
      prompt.replace(/'/g, "'\\''"),
    ], {
      timeout: 60000,
      encoding: "utf-8",
      env: { ...process.env, HERMES_YOLO_MODE: "1" },
    });

    if (result.status !== 0) {
      // Fallback: try using the LLM directly via curl
      return compileFallback(source, target, sourcePath);
    }

    let output = result.stdout.trim();

    // Strip any markdown fences the LLM might have added
    output = output.replace(/^```[\w]*\n?/gm, "").replace(/```$/gm, "").trim();

    // Add the preamble
    const timestamp = new Date().toISOString();
    const confidenceMatch = output.match(/Confidence:\s*(\w+)/i);
    const confidence = confidenceMatch ? confidenceMatch[1].toLowerCase() : "medium";

    const preamble = targetInfo.preamble
      .replace("{SOURCE}", basename(sourcePath))
      .replace("{TIMESTAMP}", timestamp)
      .replace("{CONFIDENCE}", confidence);

    // Check if output already has the preamble
    if (!output.includes("Generated by natlang")) {
      output = preamble + output;
    }

    return { code: output, confidence, target };
  } catch (e) {
    return { error: e.message, code: null, confidence: "failed", target };
  }
}

// Fallback compiler using curl to an OpenAI-compatible endpoint
async function compileFallback(source, target, sourcePath) {
  const targetInfo = TARGETS[target] || TARGETS.js;

  // Try local Ollama first (Yu's setup: localhost:11434)
  const baseUrl = process.env.NATLANG_BASE_URL || "http://127.0.0.1:11434/v1";
  const apiKey = process.env.NATLANG_API_KEY || process.env.OPENAI_API_KEY || process.env.OPENROUTER_API_KEY || process.env.GLM_API_KEY || "ollama";
  const model = process.env.NATLANG_MODEL || "glm-5.2:cloud";

  const prompt = `You are the natlang compiler. Read natural language and emit ${targetInfo.name}.

RULES:
1. Every sentence is an instruction. Emit ONLY executable code.
2. No markdown fences, no explanation. Just code.
3. Use the standard library. No external deps unless named.
4. Code must run as-is. No placeholders.
5. If ambiguous, pick simplest interpretation, add comment: // natlang: assumed X.
6. State confidence: // Confidence: high|medium|low

SOURCE:
${source}

Emit ${targetInfo.name} code:`;

  try {
    const response = await fetch(`${baseUrl}/chat/completions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [{ role: "user", content: prompt }],
        temperature: 0,
        max_tokens: 4000,
      }),
    });

    const data = await response.json();
    let output = data.choices?.[0]?.message?.content || "";
    output = output.replace(/^```[\w]*\n?/gm, "").replace(/```$/gm, "").trim();

    const timestamp = new Date().toISOString();
    const confidenceMatch = output.match(/Confidence:\s*(\w+)/i);
    const confidence = confidenceMatch ? confidenceMatch[1].toLowerCase() : "medium";

    const preamble = targetInfo.preamble
      .replace("{SOURCE}", basename(sourcePath))
      .replace("{TIMESTAMP}", timestamp)
      .replace("{CONFIDENCE}", confidence);

    if (!output.includes("Generated by natlang")) {
      output = preamble + output;
    }

    return { code: output, confidence, target };
  } catch (e) {
    return { error: e.message, code: null, confidence: "failed", target };
  }
}

// ─────────────────────────────────────────────────────────────────────
// CLI
// ─────────────────────────────────────────────────────────────────────

function main() {
  const args = process.argv.slice(2);

  if (args.length === 0 || args[0] === "--help" || args[0] === "-h") {
    console.log(`${S.bold}natlang${S.reset} — natural language compiler
${S.dim}Words are programs. Programs are words.${S.reset}

${S.bold}Usage:${S.reset}
  natlang compile <file.nl> [--target js|py|rust|html] [--run]
  natlang run <file.nl>                          (compile + execute)
  natlang new <name>                              (create a new .nl project)

${S.bold}Targets:${S.reset}
  js    JavaScript / Node.js (default)
  py    Python
  rust  Rust
  html  HTML/CSS/JS (single file)

${S.bold}Example:${S.reset}
  ${S.cyan}echo 'Create a web server on port 3000. When someone visits "/hello", respond with "world". Start the server.' > hello.nl${S.reset}
  ${S.cyan}natlang run hello.nl${S.reset}
  ${S.green}Server running on http://localhost:3000${S.reset}

${S.dim}The source is English. The output is code. The compiler is an LLM.${S.reset}`);
    process.exit(0);
  }

  const command = args[0];
  const file = args[1];

  if (!file) {
    console.error(`${S.red}Error: no file specified${S.reset}`);
    process.exit(1);
  }

  // Parse flags
  let target = "js";
  let shouldRun = false;

  for (let i = 2; i < args.length; i++) {
    if (args[i] === "--target" && args[i + 1]) {
      target = args[i + 1];
      i++;
    }
    if (args[i] === "--run") shouldRun = true;
  }

  if (command === "run") {
    shouldRun = true;
  }

  if (command === "new") {
    // Create a new natlang project
    const projectDir = resolve(file);
    mkdirSync(projectDir, { recursive: true });
    writeFileSync(join(projectDir, "main.nl"),
      `# ${file} — a natlang program\n\n` +
      `Describe what this program does in plain English.\n` +
      `Each sentence is an instruction. The compiler reads it.\n\n` +
      `# Example:\n` +
      `# Create a web server on port 3000.\n` +
      `# When someone visits "/", respond with "hello world".\n` +
      `# Start the server.\n`
    );
    console.log(`${S.green}Created ${file}/main.nl${S.reset}`);
    return;
  }

  if (command === "compile" || command === "run") {
    const sourcePath = resolve(file);
    if (!existsSync(sourcePath)) {
      console.error(`${S.red}Error: file not found: ${sourcePath}${S.reset}`);
      process.exit(1);
    }

    const source = readFileSync(sourcePath, "utf-8");

    // Remove comments (lines starting with #)
    const cleanSource = source.split("\n")
      .filter(l => !l.trim().startsWith("#"))
      .join("\n")
      .trim();

    if (!cleanSource) {
      console.error(`${S.red}Error: no source (file is all comments or empty)${S.reset}`);
      process.exit(1);
    }

    const targetInfo = TARGETS[target] || TARGETS.js;
    console.log(`${S.dim}Compiling ${basename(sourcePath)} → ${targetInfo.name}...${S.reset}`);

    compile(cleanSource, target, sourcePath).then(result => {
      if (result.error) {
        console.error(`${S.red}Compilation failed: ${result.error}${S.reset}`);
        process.exit(1);
      }

      // Write output
      const outDir = join(dirname(sourcePath), "build");
      mkdirSync(outDir, { recursive: true });
      const outName = basename(sourcePath, extname(sourcePath)) + targetInfo.extension;
      const outPath = join(outDir, outName);
      writeFileSync(outPath, result.code);

      console.log(`${S.green}✓ Compiled${S.reset} ${S.dim}[confidence: ${result.confidence}]${S.reset}`);
      console.log(`${S.cyan}  ${outPath}${S.reset}`);

      if (shouldRun && targetInfo.runner) {
        console.log(`${S.dim}Running...${S.reset}`);
        try {
          if (target === "rust") {
            // Compile rust then run the binary
            const binPath = join(outDir, basename(sourcePath, extname(sourcePath)));
            execSync(`rustc -o ${binPath} ${outPath}`, { stdio: "inherit" });
            execSync(binPath, { stdio: "inherit" });
          } else {
            execSync(`${targetInfo.runner} ${outPath}`, { stdio: "inherit" });
          }
        } catch (e) {
          console.error(`${S.red}Runtime error: ${e.message}${S.reset}`);
          process.exit(1);
        }
      }
    });
  }
}

main();